# -*- coding: utf-8 -*-
"""001 = Deixando tudo pronto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GhfZy4Dql6Q-h1khGuR5Uji39RilKx9T
"""

msg = "Olá, Mundo"
print(msg)