# -*- coding: utf-8 -*-
"""002 - Respondendo ao usuário

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ez4EIU5ph_Ywfd81Gr5ZbMGf1tODM__
"""

nome = input ("Digite seu nome: ")
print(f"É um prazer te conhecer, {nome}!")