# -*- coding: utf-8 -*-
"""003 - Somando dois números

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iIsLPFmwr2nPBsLnXwrOosRvz0wfK4nX
"""

n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro: '))
s = n1 + n2
# print('A soma entre', n1,'e', n2,'vale', s)
print('A soma entre {} e {} é igual a {}'.format(n1, n2, s))