# -*- coding: utf-8 -*-
"""004 - Dissecando uma variável

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8lRRu_Rjd35Kda9m7RYI33Kthkzx-N4
"""

algo = input('Digite algo: ')
if algo.isalpha():
    print(f'{algo} é uma letra!')
    if algo.isnumeric():
        print(f'{algo} é um número!')
        if algo.isdecimal():
            print(f'{algo} é um número decimal!')
            if algo.isupper():
                print(f'{algo} foi escrito apenas em letras maiúsculas!')
                if algo.islower():
                    print(f'{algo} foi escrito apenas em letras minúsculas!')
                    if algo.isspace():
                        print('Você não digitou nada!')