# -*- coding: utf-8 -*-
"""005 - Antecessor e Sucessor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wCss86IpAl3ri6KmESV_COg0wC7LHH7P
"""

x = int(input('Digite um número: '))
ant = x - 1
suc = x + 1
print('O antecessor de {} é {}'.format(x, ant))
print('O sucessor de {} é {}'.format(x, suc))