# -*- coding: utf-8 -*-
"""006 - Dobro, Triplo e Raiz Quadrada

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f3iXHfpvvq9sJyIzYdTE84YAkztcGzyW
"""

n = int(input('Digite um número: '))
d = n * 2
t = n * 3
r = float(n ** (1 / 2))
print('O dobro de {} vale {}'.format(n, d))
print('O triplo de {} vale {}'.format(n, t))
print('A raiz quadrada de {} é igual a: {:.2}'.format(n, r))