# -*- coding: utf-8 -*-
"""007 - Média Aritmética

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hYMBYT5_uIsYInMGSJ8Ve_A2JA5H7FIl
"""

nome = input('Nome do Aluno: ')
nota1 = float(input('Digite a 1° nota do aluno: '))
nota2 = float(input('Digite a 2° nota do aluno: '))
s = nota1 + nota2
d = s / 2
print('Nota Total = {}'.format(s))
if d>=7:
    print('Média do(a) aluno(a) {} = {} \n O aluno(a) foi aprovado(a)!'.format(nome, d))
else:
    print('Média do(a) aluno(a) {} = {} \n O aluno(a) foi reprovado(a)!'.format(nome, d))