# -*- coding: utf-8 -*-
"""008 - Conversor de Medidas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VT0svRuDRLSazhAPirSVSw4MP6d9ubOT
"""

medida = float(input('Uma distância em metros: '))
km = medida / 1000
hm = medida / 100
dam = medida / 10
m = medida * 1
dm = medida * 10
cm = medida * 100
mm = medida * 1000
print('A medida de {}m corresponde a: '.format(medida))
print('{}km'.format(km))
print('{}hm'.format(hm))
print('{}dam'.format(dam))
print('{}m'.format(m))
print('{:.0f}dm'.format(dm))
print('{:.0f}cm'.format(cm))
print('{:.0f}mm'.format(mm))