# -*- coding: utf-8 -*-
"""013 - Reajuste Salarial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1US2CGdprsjD4mRm_kRMWVKzj4mA3UMOp
"""

sa = float(input('Quanto ganha um funcionário? R$: '))
sn = sa + (sa * 15 / 100)
print('Um funcionário que ganhava R${:.2f}, com o aumento de 15%, passa a receber R${:.2f}'.format(sa, sn))