# -*- coding: utf-8 -*-
"""014 - Conversor de Temperaturas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yjS3nJEdFhvz_WvhZPXhV4UWANJxu8A3
"""

celsius = float(input('Digite a temperatura em °C: '))
print('A temperatura em Fahrenheit é {:.1f} °F'.format(celsius * 1.8 + 32))