# -*- coding: utf-8 -*-
"""015 - Aluguel de Carros

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SHo33wSHaoNxB53arSdH8QMMUskYsYWk
"""

dias = int(input('Digite o número de dias: '))
km = float(input('Digite o número de kms rodados: '))
valor = (dias * 60) + (km * 0.15)
print('O valor final a ser pago é de R${}.'.format(valor))