# -*- coding: utf-8 -*-
"""016 - Quebrando um número

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19hp6ccjL1yKoMaHGuTN-MKTefB4D6Y3D
"""

from math import floor
valor = float(input('Digite um valor: '))
print('O valor digitado foi {} e sua porção inteira é {}'.format(valor, floor(valor)))