# -*- coding: utf-8 -*-
"""017 - Catetos e Hipotenusa

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kBk5KvC85aql3kAKRT-r44C0cCa5KwjO
"""

from math import sqrt
print('Calculando a Hipotenusa')
co = float(input('Insira o valor do cateto oposto: '))
ca = float(input('Insira o valor do cateto adjacente: '))
hi = (co ** 2) + (ca ** 2)
hi = sqrt(hi)
print('A hipotenusa desse triângulo é {:.2f}'.format(hi))