# -*- coding: utf-8 -*-
"""018 - Seno, Cosseno e Tangente

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KRQUxBOFN19OOm3EDMVTxcnprC03YUqA
"""

from math import cos, tan, sin, radians
angulo = float(input('Digite um Ângulo: '))
s = sin(radians(angulo))
c = cos(radians(angulo))
t = tan(radians(angulo))
print('Segue os valores de: \n Seno: {:.2f} \n Cosseno: {:.2f} \n Tangente: {:.2f}'.format(s, c, t))