# -*- coding: utf-8 -*-
"""019 - Sorteando um item na lista

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GIBK06XBspGqjHVSFuMrXi-gdClOk0bj
"""

from random import choice
aluno1 = str(input('Digite o nome do primeiro aluno: '))
aluno2 = str(input('Digite o nome do segundo aluno: '))
aluno3 = str(input('Digite o nome do terceiro aluno: '))
aluno4 = str(input('Digite o nome do quarto aluno: '))
lista = [aluno1, aluno2, aluno3, aluno4]
sorteador = choice(lista)
print('-'*50)
print('O aluno(a) escolhido(a) para apagar o quadro é: {}'.format(sorteador))
print('-'*50)