# -*- coding: utf-8 -*-
"""020 - Sorteando uma ordem na lista

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_V9hmwSWetHmsg7FcYRCugHiG77Dksa1
"""

from random import sample
a1 = input('Primeiro aluno: ')
a2 = input('Segundo aluno: ')
a3 = input('Terceiro aluno: ')
a4 = input('Quarto aluno: ')
lista = [a1, a2, a3, a4]
ordem = sample(lista, k=4)
print('A ordem de apresentação será: {}'.format(ordem))