# -*- coding: utf-8 -*-
"""021 - Tocando um Mp3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16qXv5jjokZErtaz_KTAWsi6V9EKJuDvg
"""

"""
Não tive paciência de terminar
"""
from pygame import mixer
mixer.init()
mixer.music.load('ex021.mp3')
mixer.music.play()
input('Está ouvindo? ')