# -*- coding: utf-8 -*-
"""022 - Analisador de Textos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1btetZz8I6FFo-ymG1vPeveE1VvJAWnFT
"""

nome = input('Qual o seu nome? ').title().strip()
print('Tudo maiúsculo: {}'.format(nome.upper()))
print('Tudo minúsculo: {}'.format(nome.lower()))
lista = nome.split()
print('O nome completo possui: {} letras'.format(len(''.join(lista))))
print('O seu primeiro nome é {} e possui {} letras'.format(lista[0], len(lista[0])))