# -*- coding: utf-8 -*-
"""023 - Separando dígitos de um número

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CxPgZKXbDL5CBnVO37wqdPkWXiuoacCB
"""

num = '000' + input('Informe um número: \n').strip()
print('Unidade: {}'.format(num[-1]))
print('Dezena: {}'.format(num[-2]))
print('Centena: {}'.format(num[-3]))
print('Milhar: {}'.format(num[-4]))