# -*- coding: utf-8 -*-
"""024 - Primeiras letras de um texto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zqxi20Xf-JKqppY20Q8c52RL0PvTyE62
"""

cid = str(input('Em que cidade você nasceu? ')).strip().title()
print(cid[:5] == 'Santo')