# -*- coding: utf-8 -*-
"""025 - Procurando String

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ehqMJdUrb5lbwnA2W8oZXlS2lYiHA5sq
"""

nome = str(input('Informe seu nome completo: ')).strip()
divisao = nome.upper().split()
print('SILVA' in divisao)