# -*- coding: utf-8 -*-
"""026 - Ocorrências dentro de um texto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCo1QhSuGv420DSHqq5TLVUnonJO84LK
"""

frase = str(input('Digite uma frase: ')).strip().lower().replace(' ',"").replace('ã','a').replace('á','a').replace('à','a').replace('â','a')
print('A letra "A" aparece na frase {} vezes'.format(frase.count('a')))
print('A letra "A" aparece pela primeira vez na {}° posição'.format(frase.find('a') + 1))
print('A letra aparece "A" aparece na frase pela última vez na posição {}'.format(frase.rfind('a')+1))