# -*- coding: utf-8 -*-
"""030 - Radar de Velocidade V2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EQ03ULv8LbypnKaXD9efjkxbNe4MyN0s
"""

v1 = int(input('Digite a velocidade do veículo: '))
mt = 7.00
if v1 > 80:
     print(input('Sua multa é de {} R$'.format((80 - v1)*mt)))
else:
     print('Pode passar!')