# -*- coding: utf-8 -*-
"""031 - Par ou Ímpar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XlT58xjnWCylmTeFeB1Di95s3GE7V8Pc
"""

num = int(input('Me diga um número: '))
if num%2==0:
    print('Número PAR')
else:
    print('Número ÍMPAR')