# -*- coding: utf-8 -*-
"""032 - Custo da Viagem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tUFm0Ayi9Mu03SY5DFBonAlicHw2Ff74
"""

viagem = int(input('Digite a distância da sua viagem em Km: '))
if viagem <= 200:
    custo = (viagem * 0.50)
    print('O custo dessa viagem é de {}R$!'.format(custo))
else:
    taxa = (viagem * 0.45)
    print('A taxa para essa viagem mais longa passa a ser de {}R$!'.format(taxa))