# -*- coding: utf-8 -*-
"""033 - Ano Bissexto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yOru2IzEOESsGpIYDdnT5jANtmbIv9tC
"""

ano = int(input('Digite o ano: '))
if (ano % 4) == 0:
    print('O ano {} é um ano Bissexto!'.format(ano))
else:
    print('O ano {} não é um ano Bissexto!'.format(ano))