# -*- coding: utf-8 -*-
"""034 - Maior e menor valor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tR5I-76SVFX8tPZ8l2JrakHqZregyIRU
"""

primeiro = int(input('Digite o primeiro número: '))
segundo = int(input('Digite o segundo número: '))
terceiro = int(input('Digite o terceiro número: '))
numeros = [primeiro, segundo, terceiro]
print('O maior valor digitado foi {}'.format(max(numeros)))
print('O menor valor digitado foi {}'.format(min(numeros)))