# -*- coding: utf-8 -*-
"""035 - Aumentos Múltiplos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hKWDetrjI5e5Fk7Psj5TRagd3l-BYWhT
"""

x = float(input('Qual é o salário do funcionário? R$'))
if x > 1250:
    print('Quem ganhava R${:.2f} passa a ganhar {:.2f}'.format(x, x * 1.1))
else:
    print('Quem ganhava R${:.2f} passa a ganhar R${:.2f}'.format(x, x * 1.15))