# -*- coding: utf-8 -*-
"""037 - Aprovando Empréstimos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/132attdgv4hYuRgsWDzPVkNRtrAQplDo3
"""

print('=' * 35)
print('Programa Meu Python, Minha vida')
print('=' * 35)
casa = float(input('Qua o valor da casa? R$: '))
salario = float(input('Qual o seu salário? R$: '))
pres = int(input('Em quantos anos quer pagar? '))
pres1 = float(casa / (pres * 12))
sal = salario * 30 / 100
if pres1 > sal:
    print('Com o salário de R${:.2f}, seu empréstimo não pode ser aprovado, sentimos muito.'.format(salario))
else:
    print('Com o salário de R${:.2f}, seu empréstimo pode ser aprovado, parabéns!!.'.format(salario))