# -*- coding: utf-8 -*-
"""039 - Comparando Números

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z09VRabUkYTMS28_l-G4afprPbawd5z4
"""

n1 = int(input('Primeiro valor: '))
n2 = int(input('Segundo valor: '))
if n1 > n2:
    print('O primeiro valor é maior.')
elif n2 > n1:
    print('O segundo valor é maior.')
else:
    print('Os dois valores são iguais.')