# -*- coding: utf-8 -*-
"""040 - Alistamento Militar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xSIQzO96CRSdNwBi630_A-lB-4xuZppE
"""

from datetime import date
from time import sleep

atual = date.today().year
nasc = int(input('Ano de nascimento: '))
idade = atual - nasc
print('Quem nasceu em {} tem {} anos em {}'.format(nasc, idade, atual))
genero = input('Qual o seu gênero? Digite [m] para MASCULINO e [f] para FEMININO: ')
print('PROCESSANDO........')
sleep(3)
if genero == 'm':

    if idade == 18:
        print('Você tem que se alistar IMEDIATAMENTE!')
    elif idade < 18:
        saldo = 18 - idade
        print('Ainda falta {} ano(s) para o alistamento.'.format(saldo))
        ano = atual + saldo
        print('Seu alistamento será em {}.'.format(ano))
    elif idade > 18:
        saldo = idade - 18
        print('Você deveria ter se alistado há {} ano(s).'.format(saldo))
        ano = atual - saldo
        print('Seu alistamento foi em {}.'.format(ano))
    elif genero == 'f':
        print('Você não precisa fazer alistamento militar obrigatório.')