# -*- coding: utf-8 -*-
"""041 - Aquele classico da Média

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAdEToVojYRaZ7h_STIlpAfxlmzMJbNX
"""

n1 = float(input('Primeira nota: '))
n2 = float(input('Segunda nota: '))
media = (n1 + n2) / 2
if media < 5.0:
    print(f'Sua media foi {media}, REPROVADO!')
if 5.0 > media < 6.9:
    print(f'Sua media foi {media}, RECUPERAÇÃO!')
if media >= 7.0:
    print(f'Sua media foi {media}, APROVADO')