# -*- coding: utf-8 -*-
"""043 - Analisando Triângulos v2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ft2Yssbhnrj6XzDgMoT7scaFPBXYMOMw
"""

n1 = int(input("insira o primeiro valor: "))
n2 = int(input("insira o segundo valor: "))
n3 = int(input("insira o terceiro valor: "))
calc1 = n1 + n2 # para a verificação da conição de n3
calc2 = n2 + n3 # para a verificação da condição de n1
calc3 = n3 + n1 # para a verificação da condição de n2

aux = ""
if n1 < calc2 and n2 < calc3 and n3 < calc1:
    if n1 == n2 == n3:
        aux = "equilátero"
        # print("equilátero")
    elif n1 != n2 != n3:
        aux = "Escaleno"
    else:
        aux = "Isóceles"
    print("é possivel desenhar um triângulo {} com estes valores".format(aux))
else:
    print("não é possivel formar um triângulo")