# -*- coding: utf-8 -*-
"""045 - Gerenciador de Pagamentos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hsOtMw24FJGQE-nVRUt2V0q2mQwK-80-
"""

#CRIEI UM VETOR PARA RECEBER VALORES...
valor = [float(input('PREÇO: '))]
#FORMATAÇÃO COM AS TRÊS ASPAS PARA FACILITAR A VIDA...
print('''{:=^28}
[1] A VISTA
[2] DÉBITO
[3] 2X NO CARTÃO
[4] 3X OU MAIS NO CARTÃO
{}'''.format('THALES STORE', '='*28))
#VETOR VAI RECEBER UM NOVO VALOR E ADICIONAR UMA POSIÇÃO NOVA [1]...
valor.append(int(input('OPÇÃO: ')))
if valor[1] == 1:
#PARA PORCENTAGEM EU SIMPLISMENTE SIMPLIFICO AS COISAS 0.9 == 90%
    print('O VALOR DA COMPRA SERA DE: {:.2f} REAIS'.format(valor[0]*0.9))
elif valor[1] == 2:
    print('O VALOR DA COMPRA SERA DE: {:.2f} REAIS'.format(valor[0]*0.95))
elif valor[1] == 3:
    print('O VALOR DA COMPRA SERA DE: {:.2f} REAIS'.format(valor[0]))
elif valor[1] == 4:
    valor.append(int(input('QUANTAS PARCELAS: ')))
    print('O VALOR DA COMPRA SERA DE: {:.2f} REAIS'.format(valor[0]*1.2))
    print('E O VALOR DA PARCELA SERA DE: {:.2f} REAIS'.format((valor[0] * 1.2)/valor[2]))
else:
    print('TENTE NOVAMENTE')

#ESPERO QUE TENHA CONTRIBUÍDO.