# -*- coding: utf-8 -*-
"""047 - Contagem Regressiva

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14a5oreew-Vngi268CitxGeL1PetS52NO
"""

import time
secs = 10
for c in range(0, secs):
    print(secs)
    time.sleep(1)
    secs -= 1
print('FELIZ ANO NOVO!!!!')