# -*- coding: utf-8 -*-
"""048 - Contagem de Pares

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWNQpM09QN6Uwej0Vh4BSo1HFQu5IwIp
"""

for c in range(0,52, 2):
    print(c)
print('Acabou')