# -*- coding: utf-8 -*-
"""049 - Soma ímpares múltiplos de três

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jufhK42l1vfu0kZjXRu0A90la-77izgW
"""

s = 0
for c in range(3, 500, 2):
    t = c % 3
    if t == 0:
        s += + c
print('A soma de todos os ímpares e múltiplos de 3 entre 1 e 500 é: {}'.format(s))