# -*- coding: utf-8 -*-
"""050 - Tabuada v2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Axg4g9Vay8MaSv4VpfVeibGeO4g5KM1y
"""

n= int (input ('Digite um numero para calcular a sua tabuada: '))
for tabu in range (0,11):
    res=n*tabu
    print ( '{} x {:2} = {}'.format (n,tabu,res))