# -*- coding: utf-8 -*-
"""052 - Progressão Aritmética

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XxsY2LOjklht2ABKc1B0VXPOppV9E7Dh
"""

num = int(input('\nDigite o Primeiro número da PA: '))
razão = int(input('Digite a Razão da PA: '))
for c in range(1, 11):
    print(num, end=' ')
    num += razão
print('Acabou')