# -*- coding: utf-8 -*-
"""053 - Números Primos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UKs7ZT3tPyvaBSdsS5ttZR0R8Zs2Ts6r
"""

lim = int(input('Digite um valor limite para calcular todos os números primos até ele: '))
for n in range(1, lim + 1):
    divisores = []
    for p in range(1, n + 1):
        if n % p == 0:
            divisores += [p]
    if len(divisores) == 2:
        print(n)