# -*- coding: utf-8 -*-
"""054 - Detector de Palíndromo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WoNOqT1Xis8-f7-msLiIu3U18heD62fc
"""

frase = input("Qual a frase? ").upper().replace(" ", "")
if frase == frase[::-1]:
    print("A frase é um palíndromo")
else:
    print("A frase não é um palíndromo")