# -*- coding: utf-8 -*-
"""058 - Validação de Dados

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZTluph36T-5jWIn1AJP2JN1XKyqGAYep
"""

sexo = ''
while sexo != 'M' and sexo != 'F':
    sexo = str(input('DIgite o sexo [M/F]: ')).upper()
    if sexo != 'M' and sexo != 'F':
        print('Por favor digite a letra correta!!!')
if sexo == 'M':
    sexo = 'Masculino'
else:
    sexo = 'Feminino'

print('O sexo escolhido foi: {}'.format(sexo))