# -*- coding: utf-8 -*-
"""061 - Cálculo do Fatorial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rJmXAOCqkk-aX42u_d7rjnL3WhE6ScBH
"""

f = fator = int(input('Resolver o fatorial de: '))

resultado = 1
fatorial = ''

for i in range(fator, 0, -1):
    fatorial += str(fator) + ' x '
    resultado *= fator
    fator -= 1

print(f'Fatorial de {f}! = {fatorial[:-2]}= {resultado}')