# -*- coding: utf-8 -*-
"""062 - Progressão Aritmética v2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_o5XXKh0Ge_AYEklX_SKZ2g0R2GXpMba
"""

p = int(input('Informe o primeiro termo de uma PA: '))
r = int(input('Informe a razão da PA: '))

resultado = str(p)
decimo = p + (10 - 1) * r

while p < decimo:
    p += r
    resultado += ' → ' + str(p)

print(resultado, end=' → Fim.')