# -*- coding: utf-8 -*-
"""066 - Maior e Menor Valor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUrzAsqtSesybaxwRqTfecPArsQtLE7V
"""

cont = soma = maior = menor = 0
não = False
while not não:
    n = int(input('Digite um número: '))
    soma += n
    cont += 1
    média = soma / cont
    if n == 1:
        maior = n
        menor = n
    else:
        if n > maior:
            maior = n
        if n < menor:
            menor = n
    acabou = str(input('Quer continura? [sim/não] '))
    if acabou == 'não':
        não = True
print('Você digitou {} números e a média deles é {}'.format(cont, média))
print('O maior número é {} e o menor número é {} '.format(maior, menor))