# -*- coding: utf-8 -*-
"""068 - Tabuada v3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18alW9jDKJXrTlOUfX6_sJ7oDInDdh34n
"""

while True:
    num = int(input("Informe um número para ver a sua tabuada (Número negativo para parar): "))
    if num < 0:
        break
    for c in range(1, 11):
        print(num, "*", c, "=", c * num)
print("Fim do programa")